#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/_helpers.sh"; manual_parse_common "$@"
PYTHON_BIN="$(manual_python_for_config "$CONFIG")"; manual_style_flags "$CONFIG"
readarray -t CFG < <("$PYTHON_BIN" - "$CONFIG" <<'PY'
import sys, yaml
from pathlib import Path
cfg=yaml.safe_load(Path(sys.argv[1]).read_text(encoding='utf-8')) or {}
out=Path(cfg.get('paths',{}).get('outputs_root','outputs')).resolve()
s=cfg.get('screening',{}) if isinstance(cfg.get('screening'),dict) else {}
print(out)
print(cfg['target'])
print(s.get('input_path',''))
print(s.get('input_format','smi'))
print(s.get('smi_layout','smiles_id'))
print(s.get('header','auto'))
print(s.get('smiles_col_name','smiles'))
print(s.get('id_col_name','compound_id'))
print(s.get('cns_mpo_threshold',4.0))
print(s.get('topk',500))
PY
)
OUTPUTS_ROOT="${CFG[0]}"; TARGET="${CFG[1]}"; INPUT_PATH="${CFG[2]}"; INPUT_FORMAT="${CFG[3]}"; SMI_LAYOUT="${CFG[4]}"; HEADER="${CFG[5]}"; SMILES_COL="${CFG[6]}"; ID_COL="${CFG[7]}"; CNS_MPO="${CFG[8]}"; TOPK="${CFG[9]}"
STEP_OUT="$OUTPUTS_ROOT/step12"; LOG_FILE="$STEP_OUT/step12_screen_library.log"; mkdir -p "$STEP_OUT"
RUN_DIR="$(manual_read_run_pointer "$PYTHON_BIN" "$OUTPUTS_ROOT/step6/run_pointer.json")"
[[ -n "$RUN_DIR" ]] || RUN_DIR="$(manual_read_run_pointer "$PYTHON_BIN" "$OUTPUTS_ROOT/step5/run_pointer.json")"
[[ -n "$RUN_DIR" ]] || manual_fail_preflight "missing run pointer for screening"
manual_require_file "$RUN_DIR/artifacts/feature_schema.json" "required for featurization"
if [[ -z "$INPUT_PATH" ]]; then
  INPUT_PATH="$STEP_OUT/demo_library.smi"
  cat > "$INPUT_PATH" <<'SMI'
CCO demo1
CCN demo2
c1ccccc1 demo3
SMI
fi
manual_require_file "$INPUT_PATH" "set screening.input_path in config or use autogenerated demo"
CMD=("$PYTHON_BIN" "scripts/screen_library.py" "--target" "$TARGET" "--run_dir" "$RUN_DIR" "--input_path" "$INPUT_PATH" "--input_format" "$INPUT_FORMAT" "--outdir" "$STEP_OUT" "--smi_layout" "$SMI_LAYOUT" "--header" "$HEADER" "--smiles_col" "$SMILES_COL" "--id_col" "$ID_COL" "--cns_mpo_threshold" "$CNS_MPO" "--topk" "$TOPK" "${STYLE_FLAGS[@]}")
manual_append_overrides EXTRA_ARGS CMD; manual_run_with_log "$LOG_FILE" "${CMD[@]}"
